// For static export, we need to generate at least one static param
// This is a workaround for dynamic routes with output: export
export async function generateStaticParams() {
  // Return a minimal set of params to satisfy the static export requirement
  // The actual content will still be loaded client-side
  return [
    { id: 'placeholder' } // This will be replaced by the actual dynamic route
  ];
}

// This allows dynamic params that aren't generated by generateStaticParams
export const dynamicParams = true;