export async function generateStaticParams() {
  // Since this is a music app with dynamic album routes, we'll generate an empty array
  // as the content will be loaded client-side
  return [];
}

export const dynamicParams = true; // Allow dynamic params that aren't generated by generateStaticParams
